# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: JLOO
title-normal: by JIMBOT
email:
description: Musings of a Loobird<br /> Rendered by Mr Jimbot.
baseurl: # the subpath of your site, e.g. /blog
url: "https://janiceloo.github.io" # the base hostname & protocol for your site
author: "Janice Loo"
street_address: 1234 Somewhere Road
city: NY
state: NY
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
linkedin_url:
pinterest_url:
slack_url:

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag

# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
